# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'BusMommy' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for BusMommy
  pod 'MapboxGeocoder.swift', '~> 0.6'
  pod 'Mapbox-iOS-SDK', '~> 3.6'

end
